name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: "Setup Node.js environment"
        uses: actions/setup-node@v1
        with:
          node-version: "12"

      - name: "Install dependencies"
        run: |
          npm ci
          npm install -g vsce

      - name: Build
        run: vsce package

      - name: Test
        uses: GabrielBB/xvfb-action@v1.0
        with:
          run: npm test

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: Markdown-All-in-One-${{ github.sha }}
          path: ./*.vsix

      - name: "(debug) Upload npm log"
        if: ${{ !success() }}
        uses: actions/upload-artifact@v2
        with:
          name: "npm-debug-log"
          path: "~/.npm/_logs"
